name: fokko
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_flavorizr: ^2.3.1

flutter:
  uses-material-design: true

  assets:
    - shorebird.yaml

# FLAVORIZR CONFIG
flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios:
      targets:
        Runner:
          bundleId: dev.fokko.$flavor

  flavors:
    dev:
      app:
        name: "Fokko Dev"
        icon: "assets/icons/app_icon_dev.png"
      android:
        applicationId: "dev.fokko.dev"
      ios:
        bundleId: "dev.fokko.dev"

    prod:
      app:
        name: "Fokko"
        icon: "assets/icons/app_icon.png"
      android:
        applicationId: "dev.fokko"
      ios:
        bundleId: "dev.fokko"
